name: dotdonuts_tab
version: '1.0-SNAPSHOT'
main: senntools.dotdonuts_tab.Dotdonuts_tab
api-version: '1.21'
depend:
  - TAB

commands:
  setdonation:
    description: Used to set user donation to certain value.
    usage: /<command>

  mydonation:
    description: Used to get user donation amount.
    usage: /<command>

  star:
    description: Used to set you star on/off.
    usage: /<command> [tab/nick] [on/off]

  starcolors:
    description: Used to display all groups to player.
    usage: /<command>

  starinfo:
    description: Used to show plugin inforamtion.
    usage: /<command>

  leaderboard:
    description: Used to show server leaderboard.
    usage: /<command>